-- GENERADO por scripts/gen-seed.ts — no editar a mano.
-- Regenerar con: npm run seed:gen

insert into public.countries (code, alpha3, numeric_code, name_es, geo_name, slug, flag, population, has_region_map) values
  ('AL', 'ALB', '008', 'Albania', 'Albania', 'albania', '🇦🇱', 2800000, false),
  ('AD', 'AND', '020', 'Andorra', 'Andorra', 'andorra', '🇦🇩', 80000, false),
  ('AT', 'AUT', '040', 'Austria', 'Austria', 'austria', '🇦🇹', 9100000, false),
  ('BY', 'BLR', '112', 'Bielorrusia', 'Belarus', 'bielorrusia', '🇧🇾', 9200000, false),
  ('BE', 'BEL', '056', 'Bélgica', 'Belgium', 'belgica', '🇧🇪', 11700000, false),
  ('BA', 'BIH', '070', 'Bosnia y Herzegovina', 'Bosnia and Herz.', 'bosnia-herzegovina', '🇧🇦', 3200000, false),
  ('BG', 'BGR', '100', 'Bulgaria', 'Bulgaria', 'bulgaria', '🇧🇬', 6400000, false),
  ('HR', 'HRV', '191', 'Croacia', 'Croatia', 'croacia', '🇭🇷', 3900000, false),
  ('CY', 'CYP', '196', 'Chipre', 'Cyprus', 'chipre', '🇨🇾', 1300000, false),
  ('CZ', 'CZE', '203', 'Chequia', 'Czechia', 'chequia', '🇨🇿', 10900000, false),
  ('DK', 'DNK', '208', 'Dinamarca', 'Denmark', 'dinamarca', '🇩🇰', 5900000, false),
  ('EE', 'EST', '233', 'Estonia', 'Estonia', 'estonia', '🇪🇪', 1400000, false),
  ('FI', 'FIN', '246', 'Finlandia', 'Finland', 'finlandia', '🇫🇮', 5600000, false),
  ('FR', 'FRA', '250', 'Francia', 'France', 'francia', '🇫🇷', 68400000, false),
  ('DE', 'DEU', '276', 'Alemania', 'Germany', 'alemania', '🇩🇪', 84500000, false),
  ('GR', 'GRC', '300', 'Grecia', 'Greece', 'grecia', '🇬🇷', 10400000, false),
  ('HU', 'HUN', '348', 'Hungría', 'Hungary', 'hungria', '🇭🇺', 9600000, false),
  ('IS', 'ISL', '352', 'Islandia', 'Iceland', 'islandia', '🇮🇸', 400000, false),
  ('IE', 'IRL', '372', 'Irlanda', 'Ireland', 'irlanda', '🇮🇪', 5300000, false),
  ('IT', 'ITA', '380', 'Italia', 'Italy', 'italia', '🇮🇹', 58800000, false),
  ('XK', 'XKX', '383', 'Kosovo', 'Kosovo', 'kosovo', '🇽🇰', 1800000, false),
  ('LV', 'LVA', '428', 'Letonia', 'Latvia', 'letonia', '🇱🇻', 1900000, false),
  ('LI', 'LIE', '438', 'Liechtenstein', 'Liechtenstein', 'liechtenstein', '🇱🇮', 40000, false),
  ('LT', 'LTU', '440', 'Lituania', 'Lithuania', 'lituania', '🇱🇹', 2900000, false),
  ('LU', 'LUX', '442', 'Luxemburgo', 'Luxembourg', 'luxemburgo', '🇱🇺', 700000, false),
  ('MT', 'MLT', '470', 'Malta', 'Malta', 'malta', '🇲🇹', 600000, false),
  ('MD', 'MDA', '498', 'Moldavia', 'Moldova', 'moldavia', '🇲🇩', 2500000, false),
  ('MC', 'MCO', '492', 'Mónaco', 'Monaco', 'monaco', '🇲🇨', 40000, false),
  ('ME', 'MNE', '499', 'Montenegro', 'Montenegro', 'montenegro', '🇲🇪', 600000, false),
  ('NL', 'NLD', '528', 'Países Bajos', 'Netherlands', 'paises-bajos', '🇳🇱', 17900000, false),
  ('MK', 'MKD', '807', 'Macedonia del Norte', 'North Macedonia', 'macedonia-del-norte', '🇲🇰', 1800000, false),
  ('NO', 'NOR', '578', 'Noruega', 'Norway', 'noruega', '🇳🇴', 5500000, false),
  ('PL', 'POL', '616', 'Polonia', 'Poland', 'polonia', '🇵🇱', 36700000, false),
  ('PT', 'PRT', '620', 'Portugal', 'Portugal', 'portugal', '🇵🇹', 10600000, false),
  ('RO', 'ROU', '642', 'Rumanía', 'Romania', 'rumania', '🇷🇴', 19000000, false),
  ('SM', 'SMR', '674', 'San Marino', 'San Marino', 'san-marino', '🇸🇲', 30000, false),
  ('RS', 'SRB', '688', 'Serbia', 'Serbia', 'serbia', '🇷🇸', 6600000, false),
  ('SK', 'SVK', '703', 'Eslovaquia', 'Slovakia', 'eslovaquia', '🇸🇰', 5400000, false),
  ('SI', 'SVN', '705', 'Eslovenia', 'Slovenia', 'eslovenia', '🇸🇮', 2100000, false),
  ('ES', 'ESP', '724', 'España', 'Spain', 'espana', '🇪🇸', 48400000, true),
  ('SE', 'SWE', '752', 'Suecia', 'Sweden', 'suecia', '🇸🇪', 10600000, false),
  ('CH', 'CHE', '756', 'Suiza', 'Switzerland', 'suiza', '🇨🇭', 8900000, false),
  ('UA', 'UKR', '804', 'Ucrania', 'Ukraine', 'ucrania', '🇺🇦', 37900000, false),
  ('GB', 'GBR', '826', 'Reino Unido', 'United Kingdom', 'reino-unido', '🇬🇧', 68300000, false)
on conflict (code) do update set
  alpha3 = excluded.alpha3, numeric_code = excluded.numeric_code, name_es = excluded.name_es,
  geo_name = excluded.geo_name, slug = excluded.slug, flag = excluded.flag,
  population = excluded.population, has_region_map = excluded.has_region_map;

insert into public.regions (country_code, code, name, parent_name) values
  ('ES', '01', 'Álava', 'País Vasco'),
  ('ES', '02', 'Albacete', 'Castilla-La Mancha'),
  ('ES', '03', 'Alicante', 'Comunidad Valenciana'),
  ('ES', '04', 'Almería', 'Andalucía'),
  ('ES', '05', 'Ávila', 'Castilla y León'),
  ('ES', '06', 'Badajoz', 'Extremadura'),
  ('ES', '07', 'Illes Balears', 'Illes Balears'),
  ('ES', '08', 'Barcelona', 'Cataluña'),
  ('ES', '09', 'Burgos', 'Castilla y León'),
  ('ES', '10', 'Cáceres', 'Extremadura'),
  ('ES', '11', 'Cádiz', 'Andalucía'),
  ('ES', '12', 'Castellón', 'Comunidad Valenciana'),
  ('ES', '13', 'Ciudad Real', 'Castilla-La Mancha'),
  ('ES', '14', 'Córdoba', 'Andalucía'),
  ('ES', '15', 'A Coruña', 'Galicia'),
  ('ES', '16', 'Cuenca', 'Castilla-La Mancha'),
  ('ES', '17', 'Girona', 'Cataluña'),
  ('ES', '18', 'Granada', 'Andalucía'),
  ('ES', '19', 'Guadalajara', 'Castilla-La Mancha'),
  ('ES', '20', 'Gipuzkoa', 'País Vasco'),
  ('ES', '21', 'Huelva', 'Andalucía'),
  ('ES', '22', 'Huesca', 'Aragón'),
  ('ES', '23', 'Jaén', 'Andalucía'),
  ('ES', '24', 'León', 'Castilla y León'),
  ('ES', '25', 'Lleida', 'Cataluña'),
  ('ES', '26', 'La Rioja', 'La Rioja'),
  ('ES', '27', 'Lugo', 'Galicia'),
  ('ES', '28', 'Madrid', 'Comunidad de Madrid'),
  ('ES', '29', 'Málaga', 'Andalucía'),
  ('ES', '30', 'Murcia', 'Región de Murcia'),
  ('ES', '31', 'Navarra', 'Navarra'),
  ('ES', '32', 'Ourense', 'Galicia'),
  ('ES', '33', 'Asturias', 'Asturias'),
  ('ES', '34', 'Palencia', 'Castilla y León'),
  ('ES', '35', 'Las Palmas', 'Canarias'),
  ('ES', '36', 'Pontevedra', 'Galicia'),
  ('ES', '37', 'Salamanca', 'Castilla y León'),
  ('ES', '38', 'Santa Cruz de Tenerife', 'Canarias'),
  ('ES', '39', 'Cantabria', 'Cantabria'),
  ('ES', '40', 'Segovia', 'Castilla y León'),
  ('ES', '41', 'Sevilla', 'Andalucía'),
  ('ES', '42', 'Soria', 'Castilla y León'),
  ('ES', '43', 'Tarragona', 'Cataluña'),
  ('ES', '44', 'Teruel', 'Aragón'),
  ('ES', '45', 'Toledo', 'Castilla-La Mancha'),
  ('ES', '46', 'Valencia', 'Comunidad Valenciana'),
  ('ES', '47', 'Valladolid', 'Castilla y León'),
  ('ES', '48', 'Bizkaia', 'País Vasco'),
  ('ES', '49', 'Zamora', 'Castilla y León'),
  ('ES', '50', 'Zaragoza', 'Aragón'),
  ('ES', '51', 'Ceuta', 'Ceuta'),
  ('ES', '52', 'Melilla', 'Melilla')
on conflict (country_code, code) do update set
  name = excluded.name, parent_name = excluded.parent_name;

insert into public.region_aliases (country_code, region_code, alias) values
  ('ES', '01', 'Araba/Álava'),
  ('ES', '01', 'Álava'),
  ('ES', '01', 'Araba'),
  ('ES', '02', 'Albacete'),
  ('ES', '03', 'Alicante/Alacant'),
  ('ES', '03', 'Alacant/Alicante'),
  ('ES', '03', 'Alicante'),
  ('ES', '04', 'Almería'),
  ('ES', '05', 'Ávila'),
  ('ES', '06', 'Badajoz'),
  ('ES', '07', 'Balears, Illes'),
  ('ES', '07', 'Illes Balears'),
  ('ES', '07', 'Baleares'),
  ('ES', '08', 'Barcelona'),
  ('ES', '09', 'Burgos'),
  ('ES', '10', 'Cáceres'),
  ('ES', '11', 'Cádiz'),
  ('ES', '12', 'Castellón/Castelló'),
  ('ES', '12', 'Castelló/Castellón'),
  ('ES', '12', 'Castellón'),
  ('ES', '13', 'Ciudad Real'),
  ('ES', '14', 'Córdoba'),
  ('ES', '15', 'Coruña, A'),
  ('ES', '15', 'A Coruña'),
  ('ES', '15', 'La Coruña'),
  ('ES', '16', 'Cuenca'),
  ('ES', '17', 'Girona'),
  ('ES', '18', 'Granada'),
  ('ES', '19', 'Guadalajara'),
  ('ES', '20', 'Gipuzkoa'),
  ('ES', '20', 'Guipúzcoa'),
  ('ES', '21', 'Huelva'),
  ('ES', '22', 'Huesca'),
  ('ES', '23', 'Jaén'),
  ('ES', '24', 'León'),
  ('ES', '25', 'Lleida'),
  ('ES', '26', 'Rioja, La'),
  ('ES', '26', 'La Rioja'),
  ('ES', '27', 'Lugo'),
  ('ES', '28', 'Madrid'),
  ('ES', '29', 'Málaga'),
  ('ES', '30', 'Murcia'),
  ('ES', '31', 'Navarra'),
  ('ES', '32', 'Ourense'),
  ('ES', '32', 'Orense'),
  ('ES', '33', 'Asturias'),
  ('ES', '34', 'Palencia'),
  ('ES', '35', 'Palmas, Las'),
  ('ES', '35', 'Las Palmas'),
  ('ES', '36', 'Pontevedra'),
  ('ES', '37', 'Salamanca'),
  ('ES', '38', 'Santa Cruz de Tenerife'),
  ('ES', '39', 'Cantabria'),
  ('ES', '40', 'Segovia'),
  ('ES', '41', 'Sevilla'),
  ('ES', '42', 'Soria'),
  ('ES', '43', 'Tarragona'),
  ('ES', '44', 'Teruel'),
  ('ES', '45', 'Toledo'),
  ('ES', '46', 'Valencia/València'),
  ('ES', '46', 'València/Valencia'),
  ('ES', '46', 'Valencia'),
  ('ES', '47', 'Valladolid'),
  ('ES', '48', 'Bizkaia'),
  ('ES', '48', 'Vizcaya'),
  ('ES', '49', 'Zamora'),
  ('ES', '50', 'Zaragoza'),
  ('ES', '51', 'Ceuta'),
  ('ES', '52', 'Melilla')
on conflict (country_code, alias) do update set region_code = excluded.region_code;

select public.refresh_affiliate_stats();
